### PR TITLE
Added javascript parser

### PR DESCRIPTION
**Pull request by samarion**

### CODE REVIEW

**Comment by zommerfelds** [comment]
Nice, so you wrote it from scratch :)
LGTM

**Comment by pwalch** [comment]
Very good @samarion. I suggest you continue with Python on Monday, C++ on Tuesday and Fortran on Wednesday :smirk:

**Comment by samarion** [comment]
Haha I think this time I'm really done with parsers. I got it over with quickly so I could start working on other parser-free things.

**Comment by amirsh** [comment]
:+1: for what @samarion said at the end :stuck_out_tongue_winking_eye:

**Pull request merged**
