### PR TITLE
Feature renaming

### PR DESCRIPTION
**Pull request by pwalch**
Renamed some stuff according to what I discussed with @samarion.

### CODE REVIEW

**Comment by pwalch** [comment]
Still to do:
* Update readme

**Comment by samarion** [comment]
LGTM! Nice extending the CodeFileData to have size and language, we can use the same classes for devsearch-learning this way.

**Comment by pwalch** [comment]
I've modified devsearch-learning accordingly.
There is just one issue: I want to put constants for the language names instead of raw strings.

**Comment by samarion** [comment]
If you want to, but I don't feel it's necessary. It will make version management a little harder since new languages will change the data-type instead of just a string.

**Pull request merged**
